language: python
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: false
    python: '2.7'
    env: BUILD_SDIST=true
install:
- pip install -r requirements.txt
script:
- python test/__init__.py
before_deploy: echo $TRAVIS_TAG | sed 's/^.//' > version.txt
deploy:
  skip_cleanup: true
  provider: pypi
  user: qta
  true:
    tags: true
    condition: $TRAVIS_TAG =~ v[0-9]+\.[0-9]+\.[0-9]+ && $BUILD_SDIST=true
  password:
    secure: "HiRHDIKunowJ2jp10kdRymQ2JT3GGvChlyXyotQC71P4FmTRj45ZRDRUc11ouCvhAWE/I26ThevUJAKcUcJw+MV2/sXz5edVHlE7TSOvSSJHQlLFO1yOIAks6W3dZan2A4NYi32TOFTNkh0jODxjSgkuLAZUwpdmFCMtofvoyEuPCXI2A9udppx1nnJ/eMWI+ddoj9yEqm3EcFdF2VFXlPyg6AtbXpl1121nPKCeUz4ce17gQJlByX108mVWp2F2gNcMQuNIIWab3cBZHBiVYFPWYtobji9M7asPg+cB4UMGBxdT6ZB4VZAjjBMUV4ZJ4QM+BA+fjhVw5n+RzUgRyjRYyP614KB5kgZtVSaZ2U76RdJIPvaUDLR6mn6urldto5kaAIwT5EycN8ClBpgigIrk4LaHBkOagOuPQqLe2pshqcJJuGlRO1c7RZ4I3rg8TkiNZ83PpCjJwQkgY6HeewrQM8Q8osQOJ6I/B2lovvyYaVHWyOg12zSbvNoW2f4MG/xwIC7Uc3FdJGF49bbbg86YoUvfF4LqJHQq5rayLMIqpRzf33vVjXBu1OgX5eN2V6SRGTf0xIPx4hr/yXZdUQOR9wjeAaKb33xDcLlTHcDen5O7gThS+A2MlB+Zigo1f901jfxh966UWCYEPlFaUOnGZhMUV5qDgkN58hp677c="