language: python
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: false
    python: '2.7'
    env: BUILD_SDIST=true
install:
- pip install -r requirements.txt
script:
- python test/__init__.py
before_deploy: echo $TRAVIS_TAG | sed 's/^.//' > version.txt
deploy:
  skip_cleanup: true
  provider: pypi
  user: qta
  true:
    tags: true
    condition: $TRAVIS_TAG =~ v[0-9]+\.[0-9]+\.[0-9]+ && $BUILD_SDIST=true
  password:
    secure: "mJKEaFtUJACJ5nJ+aAEbBbkFdljG30fWwHpzfP9H0jHxLCjio6/QHX+82w5s2Dm9RjDY2c2Pw2rvmk5gatXl7Mbmrfo+p9sfVGlbD3ii/GwAEYFSoDB2S+CRqfj8p8n0GgIaWFVPJd1b8fN1jCh3yc8g3UTL9/KvH1CDeoIX1a07UueQIEbgXgMcDhjg6n1xfXfVqlw53KLdOyoBgOW1vw4eO0vTNa2S8B3Ej2tD2WSZhu230uws+77rTz42DxPbmVaQPpo3yk6Awb6Q4qsGsPbIMYFoiTEujtnQNgRU6fh/+Cqe0fLkFCuxB3Gr8LTjkGpGoTvLor/PwMfAwtsdTOdPUPKsQkSBwO4BmtWkr+Oz7HQzKLjejPOocoEJM6xaQG6qL0JtWOJhnM9HsR1Al+U0n8RRqbeNasyqi5ZohzQBXzMduWEpZi2G87VTBIu4rqtGTHb37L2/K13LqkI92o3L89LEfUIAIF5EQteTkCIsvoJceC9ret6/7Jsn7CGMivUXyBUPfEoWcXyUQh6AIx17rBfSxQWWPNsJoWvQc7oHP8nKBk0fN1fKCUHyf306OCLG3G2/338uOUso12w42oj1vFoGLT2T45SrvrAF5EjrEp9vzLF7qtu+8OF44jvqDPTnarYmWXq91kPd8k7birSPkzvxgE8/D2J5tQMZWAI="