language: python
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: false
    python: '2.7'
    env: BUILD_SDIST=true
install:
- pip install -r requirements.txt
script:
- python test/__init__.py
before_deploy: echo $TRAVIS_TAG | sed 's/^.//' > version.txt
deploy:
  skip_cleanup: true
  provider: pypi
  user: qta
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ v[0-9]+\\.[0-9]+\\.[0-9]+ && $BUILD_SDIST=true"
  password:
    secure: KJfpBwijbYyxi8mk4vCpkFQtS72h7DbzyozPPqyYw/01ts1S7G4qaeYjZDWIMfwx7mIvopxmDkk7Fg0hDR4RzED+Zo+1foEE2dZnF4wQpRTtDyrjW4E5/v/X1QZicCvj5sS56CGqnu5TMJU23doBLnzAPbGq+SaBSqSiciiUYCkL4DLABy4yN9LzPPaTGWyH7mQHZOivBps2UoqDkXk/60Pt28/NB4OIhaKoOrPz16tQQi2kDprl93Mqgsq4LzysF18FmqLumIGvN2d14Bsg/GpnLgT3mxHdz4zLUHxnzLVh9ZIhnm6DDwu3KuYTD6YDSCbSbdVDYe6svqY9F063cEq9xuLG/nbExsKSAnzlJo9XS1sCExvfhuvcJ19D9OOjjJOQgnS004W7LW5KsCjrQuyNRpLzsm07cZBr5i27PUAZ1WT6ogNPfDkpBhsY4igaGRRl50x7ROEoS7kTn8AZQorLGgry5NzD6RtDw/hQCrd+x8EAfEWxb+E0a8Vk1PSw63S2K3LzEr1JxoRghHtvKrX+IzvXds92pke/Qt4UWGUTKt8vhqu/yGdB6uLFqcF3H7swZg+7KVAKxQAx/P/hIL6CLh5UOuk68Q1fzgKx3KeM7O3sqlC+udquRIJqYl3hGPsD6PX9FwZzQoDm5tqywZHlyC6g7ACQBwRTVpZGLX0=
