language: python
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: false
    python: '2.7'
    env: BUILD_SDIST=true
install:
- pip install -r requirements.txt
script:
- python test/__init__.py
before_deploy: echo $TRAVIS_TAG | sed 's/^.//' > version.txt
deploy:
  skip_cleanup: true
  provider: pypi
  user: qta
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ v[0-9]+\\.[0-9]+\\.[0-9]+ && $BUILD_SDIST=true"
  password:
    secure: 6TREFJ3J3EeQ+3gSqw/yO57UWcSteWIyR8/KqZYQLUztg2Qof94KRoH9h96R+tagpqHPDefTqvIw4MfB7NXt0p3MB5rt4bQknjn+g0RYWoE+kFlLgStoy0shVseds75Od0VaNCOGr/gC2DNDF+JO4x6RK1IT4bx+UvpXrYCZ6K1EOUSl4J8/pQFrMR2oBevPWp/dhwDlZ69vcirXaYx2ZETGRMiea0ESw2vsfezgy9btBTYhhMMuebe60g358orDS6XzTX8vp7B7d75I/FlwkEW/JUGgRMEpGo/cEh1GSCypRjs6Nnx47ZAsCMU3oipI3opNHoLaso3p+NxLRdOoCtDy7xyOojPc3M+33HjD0ysSnombktj3KSo9OzD8KTE+X6TWuVcEHfB8sy8OnP+E04RRZga/ql/LKfIUl/r39UeUgn9bx7Z+WH950g4ZMmykQGFU/WeEuMDcjSzZOCjG7MSm0qXgvSOhipToU3VoCwGdW+sFtrCRLR51klblnFmAZixZAD0se1iUKVaJKsuXxFQptDe1uyNBLY9c7RO5di4v8hrylD65zPr1XOrWUNVFBJ3ExDWJsjocgKO+yFpQIYpE/sCPe3TO64zx51xTbLtDHi9Xwn3+JNp9s0oHs0dMhGgTeJOfCOOFwZmMOQKv/xCSp73IL3wJkYjr/biTZ6M=
