language: python
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: false
    python: '2.7'
    env: BUILD_SDIST=true
install:
- pip install -r requirements.txt
script:
- python test/__init__.py
before_deploy: echo $TRAVIS_TAG | sed 's/^.//' > version.txt
deploy:
  skip_cleanup: true
  provider: pypi
  user: qta
  password:
    secure: "KgIQwFo3TvY5MAQOK1PptnObGuZamxF4aWhXY3gJoAqyBhyi9nYkIZ42JbNfM41Qko5uqxxwtI2NaGPNwe8xfnqZIw4YJ4S+URbGK8ASaXjIK2c+kuo4f4yjmo0Zz9T9Cl3IyPLgcARmOWeVTQ08NUQz3gUuAS64jlAbpJ47LWrAzU8KmXmJomoTJuDwHzV0vVfoYaMijOKbK7KrzgUIR2ccaq+emqWe21oiCZWvpl1YrMn4adKg1aThnKgSFCuuQTPWKFsJM0crZ5/YBe/BoDRC71x2N4yIrBSkP5nRYAuQTMDSAb3SOWL8lprxYlC9KVeoMJsAE0RvnPlf3fVhRvYaZDFk/GD9VI4udOsUMf0wyLtNZAUjQjL2hODQHsOOxzk3o3t4AGuEMmv6bME578dRfi0KMaw0pUPiaWqPu/hZbMiE6gwRRKTy8aPVkEcGGRDTP/LRujCou75BjXCJ2x/fqBoHn5M1u3dYJEC0sx7oFt3LdP2hyO7wkL63ablOfHalyPKZ/DlBU+GabLEGOX7t3E1cYl8rDNXZ3uefLFuPIPpeCnqZ3S/3bF5oxz4ELITv9pMnhIJ5YKYwwPSmg8sV3ZIP/tSQQ/L0HLqG4QBAmgEXBgt4a6ailcRhNtoS6QBsazNZcOT6gSrL6fm9cGoaL19rPg2SWBjmWSOXiZw="
  on:
    tags: true
    condition: $TRAVIS_TAG =~ v[0-9]+\.[0-9]+\.[0-9]+ && $BUILD_SDIST=true
