language: python
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: false
    python: '2.7'
    env: BUILD_SDIST=true
install:
- pip install -r requirements.txt
script:
- python test/__init__.py
before_deploy: echo $TRAVIS_TAG | sed 's/^.//' > version.txt
deploy:
  skip_cleanup: true
  provider: pypi
  user: qta
  password:
    secure: rII/NtfsjUQHaGqrzrHHuB3OWbkLNQPaYCgRoL33yuVt46kQiSGn3PXg01x+nRfVTQLKkndT6A5Bi7hmsmaV97D4WJG9pMEeMic/tf8jmZqu2i2O/1pXE2XQLGqlEwn01sBAQWttvdyFZ7vx7BRioJp2X0BE6FzKBS2KbIRqe5a4yk/YVcC+UD5mhSgQoGF6D8WkG4W2sRXgS5KCkuvQRTG0BbPZyqBr0PuM0L1CzuYz5NmTAdiEFbkg+RcE/iW+b1kGiE5uwt0OIV1gAm8DpY3crb8VSx/1m+MgSy8ljC1kjQpyVLXJ5tq9f1HxFT/CWHOFX0eOe3qt/pH1QUaLiIQ5WQVm8pDjITRIZFeIYOzUDfEX2tP4nLVz7wkJc5q6IIxhlyrpUn5wJQVqyIGZsM+RSFBo7/I24UrXU5Y3qHyOzhT3V+15wnzYbIXTynrQ+HHMHiHWCVhVWC+rxvHLtimgDAKQhP3HKGyE4SY+XItqLoyI4yOk02CIlKZM2SDxdJXKa17i73zlyfCsXJobe3F2kmr43xcauYdNSLaSqVQZ3TvcGXlal1ZR05+6S0C3u+2M43BfSV60UgJ/87qZFSCnh1BhKJu2hTBYktrZOc7FgnlXkHWrb2EIAhWwtbrAbb/kiWF2Iym13A8rQduETQpmczaH0SbR32Hljt0GFB0=
