language: python
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: false
    python: '2.7'
    env: BUILD_SDIST=true
install:
- pip install -r requirements.txt
script:
- python test/__init__.py
before_deploy: echo $TRAVIS_TAG | sed 's/^.//' > version.txt
deploy:
  skip_cleanup: true
  provider: pypi
  user: qta
  on:
    tags: true
    condition: $TRAVIS_TAG =~ v[0-9]+\.[0-9]+\.[0-9]+ && $BUILD_SDIST=true
  password:
    secure: "dW66f28GTWe10cL2kJYbxAvFwIXtjLNhsbyJOp+cmtyOc3kwllxoMY2RYWv2VNRLFyZjTKonTi8fLt9gelIMnjkFPSO623XjrqveOzElEYrAXBEB0KuKteiKNH9DsHfUEp3F1wQek2sBBA6sSz5lutHseY2RG4CaAf1GE2VjPkX65yh/Prs8Zf4pF9iknzdtslKUrBT36lI0DOFkNdubv2l0cVdY3QYwvU286pxE0+MIYMf7M8DXpa/wLon9JOOYMUn8TVcikHucT8L26wp+2G8MQ8GdzntVmie8chYfH+aFDX2I47Nkg7JyyEDGzBYPsUv/ISg61Sn+mw9qgOWwzX9zpQ6LN1lqkF6wQr43o+4pSlFqsGlA3PHcgeQh2bWuNkjw21VHTuzA197aQAF31CbUQO/sR797yNa+XgjUQCNGBy+GVdAchSahdTz88dKTBtaOUNaXIRRc2bv+h/Nx8Refnx5RlN2elu83Rv0lSqquAtK8TGMWkEKGbpcUdcZXa57o/1bfBICFhl9fPpGBkklbcTnIAeaoAkSTHuJui7YE8x+rF//mmeO4VMyAVZXj0GmIsx9mgrS7x/NixlBve9+3rcZLnzj6Em3HME2/0OpOPH99LsMJ7HgyNXZNslOJ9qvF9NWAYyF9zJhlXlatLQ6I+C9o63A/LjGFFZaHhwo="
   