language: python
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: false
    python: '2.7'
    env: BUILD_SDIST=true
install:
- pip install -r requirements.txt
script:
- python test/__init__.py
before_deploy: echo $TRAVIS_TAG | sed 's/^.//' > version.txt
deploy:
  skip_cleanup: true
  provider: pypi
  user: qta
  password:
    secure: "DLboFHIdUj0iyT8aCx+9Iy+JEwSl+VjjioKBn4sqRy1MwM85at0CXqvUAC39qoTKmBiq29j2Bdy0ZByjq4CB0h27shaohMHYy3XXl2rOCIIyGhuRYg3VU12+nTO1FgyDPJG9k/0mrnfKy7hS4Wvs0DeGE5Qj9FshJCn1DN9LTAuuTM23uGDeOVrQ73bUP9oYvYN++HbTwDM58ApmYznLF2KXaUzyJJ4+S+s0phLg64erGJTYtPZJ25BI8iTHGkBhcWsqff/Lhq7K/dOUykURwaJqwlkVkZHwt/O1/so3YNoQU+UnM5yNLvMx7z2WPA3R/1vh4+yww8KVHEg++umoWjm/Ylz+dUJuaisMV4GaDPSToSb5PxsNJSKxqrVoah7eyEdwqGLmv5hf4+9wqpPD/mVALeLfTa2NzgTAQzMJQot0GmpmvmY+N1fiSG795VWB4ggyI/YGFjsAix5HmFFOsZ9+eSpGIqgHT3i1V2NYSFEozAyh3Z9OwSreCT+jwxBZi2Y+HwIqBbgtjOw+2qnupLu/myNGhkMj3qEUT/Sqe8lF07oTmfmuWxSZp7W4nudR1RmhUKoWzsUpKXuAcjMBVCt9QTn8uy1pYJxBc/NwuUolp3Zb9zQRcRhLOtvSw7Bk6nSrYuwE5vX4JnA5gpnmgIBrAXaazbtkgLfmnTruPpo="	
  true:
    tags: true
    condition: $TRAVIS_TAG =~ v[0-9]+\.[0-9]+\.[0-9]+ && $BUILD_SDIST=true
