language: python
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: false
    python: '2.7'
    env: BUILD_SDIST=true
install:
- pip install -r requirements.txt
script:
- python test/__init__.py
before_deploy: echo $TRAVIS_TAG | sed 's/^.//' > version.txt
deploy:
  skip_cleanup: true
  provider: pypi
  user: qta
  password:
    secure: "xqKbB4+LBXIfckB5xx97hDOgpVHfzhe/oDiq4wdgRAtrpZdA7sdd6ykTElMh+K2s4xPL7g9hbTWghtfoxF9HKq2EhXd4qTJXHzdiGzMfMafmfe9Hc5t6xykUP3NwsEV5b5qlVael4HpyQZGvoU2dLhQTTMAMzRCKRjYMOn+1Nv343QBhDGw+iBlzJcyRmbu0OK7ggG7JaC82/LSj37V3ilBbE6rJXHGTput1Hm1msoV9J3MBabyqumcoR77Tw9IJYRGeQT8TdC04knvEeMj3gsj3Xk8TTimCJ2888ADvcSvgqXctkRlc1m8J1sPgsMjdDFCdYAF4ap45lFKAhulH90HFdd7g+pJut+c4y2osFKNqZ9Bsbi4lxfgiBvD7IL7FM29Gqc6r88DecBMpi1v0hAkp1tNqtUkFt+j7zMpa/nOG+jED5WagWiEn1MWHnRclNxKyGuZ5MakU1VZeCi+3/i2NGkOPClJOpJ/Cwmq4JE7i5wcvBgbyJtWBrc59ZmdIth/lYDYBqxC7l8LoLdG/QoWlpP6xz6qCf+935yas4H0mNbGpYnBPvsfMT4YOvM9RtDKSXwCl8PlhHg56iJoVrxioEEZgwuZkKNd0jCBKS8EHvmrN4XX6YAIBCFTkV6ecTMqI42OO5/hFaPEeyhAgxVaknVd4GOKQjyZIv0GcB3E="
  on:
    tags: true
    condition: $TRAVIS_TAG =~ v[0-9]+\.[0-9]+\.[0-9]+ && $BUILD_SDIST=true
